### PR TITLE
Merging Aingty's branch

### PR DESCRIPTION
**Pull request by Aingty**
I've added the SQL code to create our Database. Also I removed all of those "filename.pages" files since they pertain to my Mac version of "MS Word". They are not useful to anyone!

### CODE REVIEW

**Review by Kunaledge — APPROVED** [review]
Bueno

**Comment by ChristopherBThai** [comment]
amazing.

**Review by ChristopherBThai — APPROVED** [review]
Amazing

**Review by bpbrianpham — APPROVED** [review]
wheres the recycling bin? lolol

**Pull request merged**
